services:
  backend:
    build:
      context: ./backend
    ports:
      - 8001:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/backend
    command: >
      sh -c 'gunicorn backend.wsgi:application -b 0.0.0.0:8000'

  db:
    image: postgres
    env_file:
      - ./backend/.env.docker

  redis:
    image: redis
    hostname: redis

  worker:
    build:
      context: ./backend/
    links:
      - redis
    depends_on:
      - redis
    hostname: worker
    entrypoint: celery
    command: -A backend.celery_app worker --loglevel=info