services:
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/backend
      - static_volume:/ClothingShop/backend/static
  frontend:
    build: 
      context: ./frontend
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend


  db:
    image: postgres
    container_name: postgres
    env_file:
      - ./backend/.env.docker
    ports:
      - 5432:5432
    expose:
      - 5432

  redis:
    image: redis
    hostname: redis

  worker:
    build:
      context: ./backend/
    
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - ./backend/.env.docker
    hostname: worker
    entrypoint: celery
    command: -A backend.celery_app worker --loglevel=info

volumes:
  static_volume:
