# Generated by Django 5.0 on 2024-08-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fullname',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
