# Generated by Django 5.0 on 2024-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ManyToManyField(related_name='cat', to='shop.category'),
        ),
    ]
